name: release-package
env:
  ui-dir: media-ui
  server-dir: media

  # 打包时使用的分支
  ui-ref: master
  server-ref: master
  # 最终jar包名称
  jar-name: media-2023.5-1.jar
  # pom.xml中的工程版本
  version: 0.2.1-alpha
on:
  push:
    branches: [ master, package-*, github-actions ]
jobs:
  build-executable-jar:
    name: 编译可执行jar包
    runs-on: ubuntu-latest
    steps:
      - name: 拉取前台代码
        uses: actions/checkout@v3
        with:
          repository: wrote-code/media-ui.git
          ref: master
          path: media-ui

      - name: 设置node环境
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
          cache: yarn
          cache-dependency-path: media-ui/yarn.lock

      - name: 编译前台代码
        run: |
          echo ::group::当前环境
          cd media-ui
          echo node版本
          node -v
          echo yarn版本
          yarn -v
          echo ::endgroup::

          echo ::group::安装依赖
          yarn install
          echo ::endgroup::

          echo ::group::编译
          yarn build
          echo ::endgroup::

      - name: 拉取后台代码
        uses: actions/checkout@v3
        with:
          repository: wrote-code/media.git
          ref: master
          path: media

      - name: 设置java环境
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: 复制前台产物和发行说明到静态文件目录
        run: |
          cd media
          echo ::group::复制前台产物
          mkdir src/main/resources/static
          cp -rv ../media-ui/dist/* src/main/resources/static
          ls -a src/main/resources/static
          echo ::endgroup::

          echo ::group::复制发行说明
          cp -v releasenote.html src/main/resources/static
          cp -v ../media-ui/releasenote-ui.html src/main/resources/static
          echo ::endgroup::

      - name: 设置git提交哈希值
        run: |
          cd media-ui

          echo ::group::前台代码版本
          git log -1
          touch ../media/src/main/resources/static/ui-$(git rev-parse ${{env.ui-ref}})
          git log -1 >> ../media/src/main/resources/static/ui-$(git rev-parse ${{env.ui-ref}})
          git branch --show-current >> ../media/src/main/resources/static/ui-$(git rev-parse ${{env.ui-ref}})
          echo ::endgroup::

          echo ::group::后台代码版本
          cd ../media
          git log -1
          touch src/main/resources/static/server-$(git rev-parse ${{env.server-ref}})
          git log -1 >> src/main/resources/static/server-$(git rev-parse ${{env.server-ref}})
          git branch --show-current >> src/main/resources/static/server-$(git rev-parse ${{env.server-ref}})
          echo ::endgroup::

      - name: 编译后台代码
        run: |
          cd media

          echo ::group::环境版本::
          echo maven版本
          mvn -v
          echo java版本
          java -version
          echo ::endgroup::

          echo ::group::编译
          mvn -B clean
          mvn -DskipTests=true -B package
          echo ::endgroup::

          echo ::group::重命名jar包
          mv -v target/media-${{env.version}}.jar target/${{env.jar-name}}
          echo ::endgroup::

      - name: 上传完整制品
        uses: actions/upload-artifact@v3
        with:
          name: 可执行jar包
          path: media/target/${{env.jar-name}}
